#!/usr/bin/perl -w

use strict;
use FindBin;
use lib $FindBin::Bin;
use hyunlib qw(forkExecWait);
use wGetOptions qw(wGetOptions wpod2usage);

my $vcf = "";
my $out = "";
my $key = "";
my $sepchr = "";
my $keep = "";
my $binbgzip = "$FindBin::Bin/bgzip";
my $bintabix = "$FindBin::Bin/tabix";
my $bcftools = "/usr/cluster/bin/bcftools";
my $binliftOver = "/net/fantasia/home/hmkang/tools/ucsc_tools/executables/liftOver";
my $chain = "";

wGetOptions(
    "-LiftOver a VCF file",
    "--Required Options",
    "vcf=s",[\$vcf,"Input VCF file"],
    "out=s",[\$out,"Output file. STDOUT if unspecified"],
    "chain=s",[\$chain,"liftOver chain file"],
    "liftover=s",[\$binliftOver,"Path to binary of liftOver tool (downloadable from UCSC)"],
    "bcftools=s",[\$bcftools,"Path to binary of bcftools"],    
    ) || wpod2usage(2);


wpod2usage(2) unless ( ( $vcf ) && ( $out ) && ( $chain ) && ( $binliftOver) ) ;

if ( $vcf =~ /\.bcf$/ ) { open(VCF, "$bcftools view $vcf|") || die "Cannot open file\n"; }
elsif ( $vcf =~ /\.gz$/ ) { open(VCF,"zcat $vcf|") || die "Cannot open file\n"; }
else { open(VCF,$vcf) || die "Cannot open file\n"; }

open(BED,">$out.old.bed") || die "Cannot write $out.old.bed";
open(OUT,"| $binbgzip -c > $out.vcf.gz") || die "Cannot open file\n";

my %h = ();
while(<VCF>) {
    if ( /^#/ ) {
	print OUT $_;
	next;
    }
    my @F = split;
    my $key = "$F[0]\_$F[1]\_$F[3]\_$F[4]";
    unless ( $F[0] =~ /^chr/ ) {    
	$F[0] = "chr$F[0]";
    }
    $h{$key} = \@F;
    print BED join("\t",$F[0],$F[1]-1,$F[1]+length($F[3])-1,$key)."\n";
}

close BED;

&forkExecWait("$binliftOver $out.old.bed $chain $out.new.bed $out.unmapped.bed");

open(IN,"cat $out.new.bed | sort -k 1,1 -k 2,3n |") || die "Cannot open $out.new.bed";
while(<IN>) {
    my ($chr,$beg,$end,$key) = split;
    next unless ( $chr =~ /^chr(\d+|X|Y|M)$/ );
    if ( $chain =~ /ToHg19/ ) {
	$chr =~ s/^chr//;
    }
    my @F = @{$h{$key}};
    $F[7] .= ";OLD_VARIANT=$key";
    print OUT join("\t",$chr,$beg+1,@F[2..$#F])."\n";
}
close IN;
close OUT;

my $cmd = "$bintabix -pvcf $out.vcf.gz";
&forkExecWait($cmd);

